# Generated by Django 3.1.1 on 2020-09-16 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 16, 16, 16, 58, 194151)),
        ),
    ]
