# Generated by Django 3.1.1 on 2020-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_auto_20200918_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='unique_code_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
